tasks:
  - name: Install AWS CLI
    init: |
      # Download the AWS CLI installer
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      
      # Unzip the installer
      unzip awscliv2.zip
      
      # Run the installer
      sudo ./aws/install

      # Enable AWS CLI Auto Prompt feature
      export AWS_CLI_AUTO_PROMPT=on-partial
      
      # Clean up temporary files
      rm -rf awscliv2.zip aws/