tasks:
  - name: Install AWS CLI
    init: |
      cd /workspace
      # Download the AWS CLI installer
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      
      # Unzip the installer
      unzip awscliv2.zip
      
      # Run the installer
      sudo ./aws/install
      
      # Clean up temporary files
      rm -rf awscliv2.zip aws/

      cd $THEIA_WORKSPACE_ROOT
